network: agoric-emerynet
folder: '.agoric'
daemon: ag0
chain_id: 'agoric-emerynet-1'
node_version: 'agoric-upgrade-6'
repo: 'https://github.com/Agoric/ag0'
genesis: "https://emerynet.rpc.agoric.net:443/genesis"
seeds: "0f04c4610b7511a64b8644944b907416db568590@34.173.97.225:26656,fb86a0993c694c981a28fa1ebd1fd692f345348b@34.172.187.8:26656"
#peers: "fb86a0993c694c981a28fa1ebd1fd692f345348b@34.172.187.8:26656"
custom_port_prefix: 44

# [Optional] Cosmos exporter
denom: bld
denom_prefix: agoric

# [Optional] Snapshot
snapshot_server: 2
snapshot_hour: 4
snapshot_minute: 30
#snapshot_method: 'aws'
#snapshot_method: 'gcloud'
snapshot_method: 'rclone'
snapshot_storage: 'gcs'
take_snapshots: false
restore_snapshots: false
snapshot_bucket: '{{ vault_snapshot_bucket }}'
gcloud_project_number: '{{ vault_gcloud_project_number }}'

# sensitive data
#gcp_token: "{{ vault_gcp_token }}"

# [Optional] Statesync 
use_statesync: false
statesync_uri: 'http://10.10.69.226:44657'

# [Optional] Expose node p2p publicly (note: only works on relayer role)
expose_public_ip: false

# repo for cosmos-pruner
# required for backup role if take_snapshots == true
cosmprund_repo: 'https://github.com/binaryholdings/cosmprund'

use_pex: true
genesis_processing: "jq"
