network: agoric
folder: '.agoric'
daemon: agd
chain_id: 'agoric-3'
#node_version: 'agoric-upgrade-7-2'
#node_version: 'pismoA-rc4'
#node_version: 'pismoB'
#node_version: 'agoric-upgrade-9'
#node_version: "pismoD"
#node_version: "mainnet1B-rc3"
node_version: "agoric-upgrade-11"
repo: 'https://github.com/Agoric/agoric-sdk'
genesis: 'https://main.agoric.net/genesis.json'
seeds: 'ecb5a8127b6d6ce8ee2ee40678a3bb69af04d8e4@10.10.50.110:44656,524f657dbca01fdebbebcb3f85873608237ce967@10.10.50.111:44656'  # zd-agoric-relayer-0, # zd-agoric-relayer-1
peers: 'ecb5a8127b6d6ce8ee2ee40678a3bb69af04d8e4@10.10.50.110:44656,524f657dbca01fdebbebcb3f85873608237ce967@10.10.50.111:44656'  # zd-agoric-relayer-0, # zd-agoric-relayer-1
custom_port_prefix: 44

# [Optional] Cosmos exporter
denom: bld
denom_prefix: agoric

# [Optional] Snapshot
snapshot_server: 2
snapshot_hour: 4
snapshot_minute: 30
#snapshot_method: 'aws'
#snapshot_method: 'gcloud'
snapshot_method: 'rclone'
#snapshot_storage: 'gcs'
snapshot_storage:
  - 'gcs'
  - 'b2'
take_snapshots: true
restore_snapshots: true
snapshot_bucket: '{{ vault_snapshot_bucket }}'
gcloud_project_number: '{{ vault_gcloud_project_number }}'
# sensitive data
#gcp_token: "{{ vault_gcp_token }}"
b2_account_id: "{{ vault_b2_account_id }}"
b2_application_key: "{{ vault_b2_application_key }}"
b2_bucket: "{{ vault_b2_bucket }}"


# [Optional] Statesync 
use_statesync: false
statesync_uri: 'https://agoric-rpc.zanshindojo.org:443'
# statesync_uri: 'https://agoric-rpc.polkachu.com:443'

# [Optional] Expose node p2p publicly (note: only works on relayer role)
expose_public_ip: false

# repo for cosmos-pruner
# required for backup role if take_snapshots == true
cosmprund_repo: 'https://github.com/binaryholdings/cosmprund'

# do not run peer discovery except on relayers
#pex: false

#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-5/ag0-agoric-upgrade-5-linux-amd64"
#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-6/ag0-agoric-upgrade-6-linux-amd64"
#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-7/ag0-agoric-upgrade-7-linux-amd64"
#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-7-2/ag0-agoric-upgrade-7-2-linux-amd64"

minimum_gas_prices: "0.01ubld,0.005uist"
scheduled_cleanup: false
