network: agoric
folder: '.agoric'
daemon: agd
chain_id: 'agoric-3'
#node_version: 'agoric-upgrade-7-2'
#node_version: 'pismoA-rc4'
#node_version: 'pismoB'
#node_version: 'agoric-upgrade-9'
#node_version: "pismoD"
#node_version: "mainnet1B-rc3"
#node_version: "agoric-upgrade-11"
#node_version: "agoric-upgrade-12"
#node_version: "agoric-upgrade-13"
#node_version: "agoric-upgrade-14"
#node_version: "agoric-upgrade-15"
#node_version: "agoric-upgrade-16"
#node_version: "agoric-upgrade-17"
#node_version: "agoric-upgrade-18"
#node_version: "agoric-upgrade-18a"
#node_version: "agoric-upgrade-19"
#node_version: "agoric-upgrade-20"
#node_version: "agoric-upgrade-21"
node_version: "agoric-upgrade-22a"
repo: 'https://github.com/Agoric/agoric-sdk'
genesis: 'https://main.agoric.net/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14456,400f3d9e30b69e78a7fb891f60d76fa3c73f0ecc@agoric.rpc.kjnodes.com:12759'
custom_port_prefix: 44
#network: "mainnet"

iavl_disable_fastnode: true

# [Optional] Cosmos exporter
denom: bld
denom_prefix: agoric

# [Optional] Snapshot
snapshot_server: 2
snapshot_hour: 4
snapshot_minute: 30
#snapshot_method: 'aws'
#snapshot_method: 'gcloud'
snapshot_method: 'rclone'
#snapshot_storage: 'gcs'
snapshot_storage:
  - 'gcs'
  - 'b2'
take_snapshots: false
restore_snapshots: true
snapshot_uri: "https://snapshots.kjnodes.com/agoric/snapshot_latest.tar.lz4"
snapshot_bucket: '{{ vault_snapshot_bucket }}'
gcloud_project_number: '{{ vault_gcloud_project_number }}'
# sensitive data
#gcp_token: "{{ vault_gcp_token }}"
b2_account_id: "{{ vault_b2_account_id }}"
b2_application_key: "{{ vault_b2_application_key }}"
b2_bucket: "{{ vault_b2_bucket }}"


# [Optional] Statesync 
use_statesync: true
# 1000 is normal for most cosmos-sdk chains, but agoric takes so long to take a state-sync snapshot that we need to trust snapshots that are 5000 blocks old
statesync_trust_height_offset: 2000
#statesync_trust_period: "420h0m0s"
statesync_trust_period: "168h0m0s"
#statesync_uri: 'https://agoric-rpc.zanshindojo.org:443'
statesync_uri: 'https://agoric-rpc.polkachu.com:443'
statesync_rpc_servers: "https://main.rpc.agoric.net:443,https://agoric-rpc.zanshindojo.org:443,https://agoric-rpc.polkachu.com:443,https://rpc.agoric.nodestake.top:443,https://agoric.rpc.kjnodes.com:443"

# [Optional] Expose node p2p publicly (note: only works on relayer role)
expose_public_ip: false

# repo for cosmos-pruner
# required for backup role if take_snapshots == true
cosmprund_repo: 'https://github.com/binaryholdings/cosmprund'

# do not run peer discovery except on relayers
#pex: false

#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-5/ag0-agoric-upgrade-5-linux-amd64"
#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-6/ag0-agoric-upgrade-6-linux-amd64"
#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-7/ag0-agoric-upgrade-7-linux-amd64"
#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-7-2/ag0-agoric-upgrade-7-2-linux-amd64"

minimum_gas_prices: "0.01ubld,0.005uist"
scheduled_cleanup: false

install_nodejs: true
#nodejs_version: "node_16.x"
#nodejs_version: "node_18.x"
nodejs_version: "node_20.x"
