network: agorictest
folder: '.agoric'
daemon: agd
chain_id: 'agoric-emerynet-8'
#node_version: 'agoric-upgrade-7'
#node_version: 'pismoA-rc4'
#node_version: 'agoric-upgrade-8'
#node_version: 'agoric-upgrade-9'
#node_version: 'mainnet1B-rc0'
#node_version: 'mainnet1B-rc1'
#node_version: 'mainnet1B-rc2'
#node_version: 'mainnet1B-rc3'
#node_version: 'agoric-upgrade-12-rc0'
#node_version: 'agoric-upgrade-13-rc0'
#node_version: 'agoric-upgrade-14-rc0'
node_version: 'agoric-upgrade-14-rc1'
#node_version: 'agoric-upgrade-11-rc0'
#repo: 'https://github.com/Agoric/ag0'
repo: 'https://github.com/Agoric/agoric-sdk'
#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-7/ag0-agoric-upgrade-7-linux-amd64"
genesis: "https://emerynet.rpc.agoric.net:443/genesis"
seeds: "0f04c4610b7511a64b8644944b907416db568590@35.222.138.81:26656"
peers: ""
custom_port_prefix: 45

# [Optional] Cosmos exporter
denom: ubld
denom_prefix: agoric

# [Optional] Snapshot
snapshot_server: 2
snapshot_hour: 4
snapshot_minute: 30
#snapshot_method: 'aws'
#snapshot_method: 'gcloud'
snapshot_method: 'rclone'
snapshot_storage: 'gcs'
take_snapshots: true
restore_snapshots: true
snapshot_bucket: '{{ vault_emerynet_snapshot_bucket }}'
gcloud_project_number: '{{ vault_emerynet_gcloud_project_number }}'

# sensitive data
#gcp_token: "{{ vault_gcp_token }}"

# [Optional] Statesync 
use_statesync: false
statesync_uri: 'https://agoric-testnet-rpc.polkachu.com:443'


# [Optional] Expose node p2p publicly (note: only works on relayer role)
expose_public_ip: false

# repo for cosmos-pruner
# required for backup role if take_snapshots == true
cosmprund_repo: 'https://github.com/binaryholdings/cosmprund'

use_pex: true
genesis_processing: "jq"

minimum_gas_prices: "3600ubld,0.001uist"


