network: agoric-ollinet
folder: '.agoric'
daemon: ag0
chain_id: 'agoricollinet-11'
node_version: 'agoric-upgrade-5'
repo: 'https://github.com/Agoric/ag0'
genesis: 'https://ollinet.rpc.agoric.net:443/genesis'
seeds: '0f04c4610b7511a64b8644944b907416db568590@35.184.29.159:26656'
#peers: '' 
custom_port_prefix: 44

# [Optional] Cosmos exporter
denom: bld
denom_prefix: agoric

# [Optional] Snapshot
snapshot_server: 2
snapshot_hour: 4
snapshot_minute: 30
#snapshot_method: 'aws'
#snapshot_method: 'gcloud'
snapshot_method: 'rclone'
snapshot_storage: 'gcs'
take_snapshots: false
snapshot_bucket: '{{ vault_snapshot_bucket }}'
gcloud_project_number: '{{ vault_gcloud_project_number }}'

# sensitive data
#gcp_token: "{{ vault_gcp_token }}"

# [Optional] Statesync 
use_statesync: false
statesync_uri: 'http://10.10.69.226:44657'

# [Optional] Expose node p2p publicly (note: only works on relayer role)
expose_public_ip: false

# repo for cosmos-pruner
# required for backup role if take_snapshots == true
cosmprund_repo: 'https://github.com/binaryholdings/cosmprund'