network: agoric
folder: '.agoric'
daemon: ag0
chain_id: 'agoric-3'
node_version: 'agoric-upgrade-5'
repo: 'https://github.com/Agoric/ag0'
genesis: 'https://main.agoric.net/genesis.json'
# defaults, dead
#seeds: 'a26158a5cbb1df581dd6843ac427191af76d6d5d@104.154.240.50:26656,6e26a1b4afa6889f841d7957e8c2b5d50d32d485@95.216.53.26:26656'
# zd-hz-agoric-backup
#seeds: 'fd16bfc2891270c5b490ae3d77597f33664e7031@10.10.69.223:26656'
#peers: 'fd16bfc2891270c5b490ae3d77597f33664e7031@10.10.69.223:26656'
#peers: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:44656'
#peers: '1fa3d2cd934b658e05f12a003eb5523f476173ec@65.108.131.174:44656' # polkachu state-sync
#seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:44656' # polkachu seed node
#seeds: '1fa3d2cd934b658e05f12a003eb5523f476173ec@65.108.131.174:44656' # polkachu state-sync
#seeds: ''
seeds: 'ecb5a8127b6d6ce8ee2ee40678a3bb69af04d8e4@10.10.69.226:44656,524f657dbca01fdebbebcb3f85873608237ce967@10.10.69.229:44656'  # zd-agoric-relayer-0, # zd-agoric-relayer-1
peers: 'ecb5a8127b6d6ce8ee2ee40678a3bb69af04d8e4@10.10.69.226:44656,524f657dbca01fdebbebcb3f85873608237ce967@10.10.69.229:44656'  # zd-agoric-relayer
custom_port_prefix: 44

# [Optional] Cosmos exporter
denom: bld
denom_prefix: agoric

# [Optional] Snapshot
snapshot_server: 2
snapshot_hour: 4
snapshot_minute: 30
#snapshot_method: 'aws'
#snapshot_method: 'gcloud'
snapshot_method: 'rclone'
snapshot_storage: 'gcs'
take_snapshots: true
restore_snapshots: true
snapshot_bucket: '{{ vault_snapshot_bucket }}'
gcloud_project_number: '{{ vault_gcloud_project_number }}'

# sensitive data
#gcp_token: "{{ vault_gcp_token }}"

# [Optional] Statesync 
use_statesync: true
statesync_uri: 'https://agoric-rpc.zanshindojo.org:443'

# [Optional] Expose node p2p publicly (note: only works on relayer role)
expose_public_ip: false

# repo for cosmos-pruner
# required for backup role if take_snapshots == true
cosmprund_repo: 'https://github.com/binaryholdings/cosmprund'

# do not run peer discovery except on relayers
#pex: false

#binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-5/ag0-agoric-upgrade-5-linux-amd64"
binary: "https://github.com/Agoric/ag0/releases/download/agoric-upgrade-6/ag0-agoric-upgrade-6-linux-amd64"