---
- name: Prepare
  hosts: '{{ target }}'
  become: true
  gather_facts: false
  roles:
    - prepare

- name: Main
  hosts: '{{ target }}'
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - role: node_install
    - role: node_initialize
    - role: node_configure
      tags: 'node_configure'
    - role: node_launch
