---
- name: Install from source
  block:
    - name: Clone node repo
      git:
        repo: '{{ repo }}'
        dest: '{{ user_dir }}/{{ network }}/{{ node_version }}'
        version: '{{ node_version }}'
        update: yes
        force: yes
        depth: 1

    - name: Build and Install javascript sdk
      command: '{{ item }}'
      args:
        chdir: '{{ user_dir }}/{{ network }}/{{ node_version }}'
      with_items:
        - 'yarn install'
        - 'yarn build'
      environment:
        PATH: '{{ path }}'
      when: network is defined and network is search("agoric")

    - name: Build and Install golang binary
      command: '{{ item }}'
      args:
        chdir: '{{ user_dir }}/{{ network }}/{{ node_version }}/packages/cosmic-swingset'
      with_items:
        - 'make'
      environment:
        PATH: '{{ path }}'
        GOPATH: '{{ user_dir }}/go'
      when: network is defined and network is search("agoric")

    - name: Install node
      command: '{{ item }}'
      args:
        chdir: '{{ user_dir }}/{{ network }}/{{ node_version }}'
      with_items:
        - 'make install'
      environment:
        PATH: '{{ path }}'
        GOPATH: '{{ user_dir }}/go'
      when: network is defined and network is not search("agoric")
  when: binary is undefined

- name: Install from binary
  include_tasks: binary_default.yml
  when: binary is defined and binary_processing is not defined

- name: Install from binary zipped
  include_tasks: binary_zip.yml
  when: binary is defined and binary_processing is defined and binary_processing == 'zip'

- name: Install from binary tar gz
  include_tasks: binary_targz.yml
  when: binary is defined and binary_processing is defined and binary_processing == 'targz'
