---
- name: open prometheus port
  become: true
  command: 'ufw allow {{ custom_port_prefix }}660/tcp'

- name: open p2p port
  become: true
  command: 'ufw allow {{ custom_port_prefix }}656/tcp'

- name: Create cosmovisor directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ user_dir }}/{{ folder }}/cosmovisor/genesis/bin'
    - '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades'
    - '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ node_version }}'
    - '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ node_version }}/bin'

- name: link daemon file to cosmovisor
  file:
    src: '{{ user_dir }}/go/bin/{{ daemon }}'
    path: '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ node_version }}/bin/{{ daemon }}'
    state: link
  when: network is not search("agoric")

- name: link agoric daemon file to cosmovisor (version > agoric-upgrade-9)
  file:
    src: '{{ user_dir }}/{{ network }}/{{ node_version }}/bin/{{ daemon }}'
    path: '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ node_version }}/bin/{{ daemon }}'
    state: link
  when: network is search("agoric") and node_version != "agoric-upgrade-9"

- name: copy and link agoric binaries to cosmovisor (version == agoric-upgrade-9)
  block:
    - name: copy agd binary to cosmovisor dir
      copy:
        src: '{{ user_dir }}/go/bin/{{ daemon }}'
        dest: '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ node_version }}/bin/{{ daemon }}'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0755'
        remote_src: yes
    - name: link ag-cosmos-helper daemon file to cosmovisor
      file:
        src: '{{ user_dir }}/{{ network }}/{{ node_version }}/golang/cosmos/build/ag-cosmos-helper'
        path: '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ node_version }}/bin/ag-cosmos-helper'
        state: link
    - name: link ag-chain-cosmos daemon file to cosmovisor bin dir
      file:
        src: '{{ user_dir }}/{{ network }}/{{ node_version }}/packages/cosmic-swingset/bin/ag-chain-cosmos'
        path: '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ node_version }}/bin/ag-chain-cosmos'
        state: link
    - name: link ag-nchainz daemon file to cosmovisor bin dir
      file:
        src: '{{ user_dir }}/{{ network }}/{{ node_version }}/packages/cosmic-swingset/bin/ag-nchainz'
        path: '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades/{{ node_version }}/bin/ag-nchainz'
        state: link
  when: network is search("agoric") and node_version == "agoric-upgrade-9"

- name: copy service file
  become: true
  template:
    src: 'cosmovisor.service.j2'
    dest: '/etc/systemd/system/{{ network }}.service'
    owner: root
    group: root
    mode: '0644'

- name: start cosmovisor service
  become: true
  systemd:
    name: '{{ network }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
