---
- name: install apt packages
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  loop:
    - make
    - build-essential
    - gcc
    - git
    - jq
    - chrony
    - curl
    - lsb-release

- name: Go get cosmovisor
  #command: 'go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@{{ cosmovisor_version }}'
  command: 'go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@{{ cosmovisor_version }}'
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ user_dir }}/go'

- name: Change go folder permission
  file:
    path: '{{ user_dir }}/go'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: true
    mode: '0755'

- name: copy .profile
  template:
    src: 'profile.j2'
    dest: '{{ user_dir }}/.profile'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0600'

- name: Add DAEMON_NAME line in .profile
  lineinfile:
    path: '{{ user_dir }}/.profile'
    regexp: 'export DAEMON_NAME='
    line: 'export DAEMON_NAME={{ daemon }}'
    state: present
  when: daemon is defined

- name: Add DAEMON_HOME line in .profile
  lineinfile:
    path: '{{ user_dir }}/.profile'
    regexp: 'export DAEMON_HOME='
    line: 'export DAEMON_HOME=$HOME/{{ folder }}'
    state: present
  when: folder is defined
