---
- name: install packages
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: ufw already enabled
  command: ufw status verbose
  register: ufw_status_result
  changed_when: False

- name: open node_exporter port
  command: ufw allow 9100/tcp
  when:
    - not ufw_status_result.stdout is search("9100/tcp.*ALLOW IN.*Anywhere")
    - node_exporter|bool == true

- name: open prometheus port
  command: ufw allow 26660/tcp
  when:
    - not ufw_status_result.stdout is search("26660/tcp.*ALLOW IN.*Anywhere")

- name: open p2p port
  command: ufw allow 26656/tcp
  when:
    - not ufw_status_result.stdout is search("26656/tcp.*ALLOW IN.*Anywhere")

- name: open ssh port
  command: ufw allow {{ ssh_port }}/tcp
  when:
    - not ufw_status_result.stdout is search("{{ ssh_port }}/tcp.*ALLOW IN.*Anywhere")

- name: enable firewall
  shell: |
    set -o pipefail
    echo "y" | ufw enable
  args:
    executable: /bin/bash
  when: not ufw_status_result.stdout is search("Status.* active")
