---
- meta: end_play
  when: (prepare is defined) and (prepare|bool is false)

- name: Refresh GPG keys for apt
  import_tasks: refresh_apt_gpg_keys.yml

- name: Update and upgrade the machine
  apt:
    upgrade: dist
    update_cache: true

- name: install node_exporter
  import_tasks: node_exporter.yml
  when: node_exporter|bool == true
  tags: node_exporter

- name: install promtail
  import_tasks: promtail.yml
  when: promtail|bool == true

- name: firewall setup
  import_tasks: firewall.yml
  tags: firewall

- name: install cosmos software
  import_tasks: cosmos_software.yml
  when: cosmos_software|default(true)|bool == true

- name: configure rsyslog
  import_tasks: rsyslog.yml

- name: configure vim
  import_tasks: vim.yml

- name: install nodejs
  import_tasks: nodejs.yml
  when: install_nodejs is defined and install_nodejs|bool == true
  tags: install_nodejs
