- name: Install dependencies
  apt:
    name: 
     - gnupg 
     - apt-transport-https
    state: present
    update_cache: true

- name: Ensure /etc/apt/keyrings directory exists # exists out of the box on debian >= 12
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Ensure {{ user_dir }}/.node/bin directory exists
  ansible.builtin.file:
    path: "{{ user_dir }}/.node/bin"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Add nodesource apt repository key.
  ansible.builtin.get_url:
    url: "{{ nodesource_repo_key_url }}"
    dest: /etc/apt/keyrings/nodesource.asc
    mode: '0644'
    force: true

- name: Add NodeSource repo
  apt_repository: 
    filename: nodesource
    #repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/{{ nodejs_version }} {{ ansible_facts['distribution_release'] }} main"
    #repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/{{ nodejs_version }} nodistro main"
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/{{ nodejs_version }} nodistro main"
    state: present

- name: Add preference for NodeSource for nodejs
  copy:
    dest: /etc/apt/preferences.d/nodesource
    content: |
      Package: nodejs
      Pin: origin "deb.nodesource.com"
      Pin-Priority: 1001

- name: Install nodejs
  apt:
    name: 
     - nodejs
    state: present
    update_cache: true
    allow_downgrade: yes

- name: Enable corepack
  ansible.builtin.command:
    cmd: corepack enable
  changed_when: false

- name: Configure yarn version using corepack
  ansible.builtin.command:
    cmd: corepack prepare yarn@4.9.1 --activate
  changed_when: true

