- name: Install dependencies
  apt:
    name: 
     - gnupg 
     - apt-transport-https
    state: present
    update_cache: true

- name: Ensure /etc/apt/keyrings directory exists # exists out of the box on debian >= 12
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Add nodesource apt repository key.
  ansible.builtin.get_url:
    url: "{{ nodesource_repo_key_url }}"
    dest: /etc/apt/keyrings/nodesource.asc
    mode: '0644'
    force: true

- name: Add NodeSource repo
  apt_repository: 
    filename: nodesource
    #repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/{{ nodejs_version }} {{ ansible_facts['distribution_release'] }} main"
    #repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/{{ nodejs_version }} nodistro main"
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/{{ nodejs_version }} nodistro main"
    state: present

- name: Add yarn apt repository key.
  ansible.builtin.get_url:
    url: "{{ yarn_repo_key_url }}"
    dest: /etc/apt/keyrings/yarnpkg.asc
    mode: '0644'
    force: true

- name: Add yarn repo
  apt_repository: 
    filename: yarnpkg
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/yarnpkg.asc] https://dl.yarnpkg.com/debian stable main"
    state: present

- name: Add preference for NodeSource for nodejs
  copy:
    dest: /etc/apt/preferences.d/nodesource
    content: |
      Package: nodejs
      Pin: origin "deb.nodesource.com"
      Pin-Priority: 1001

- name: Add preference for yarnpkg for yarn
  copy:
    dest: /etc/apt/preferences.d/yarnpkg
    content: |
      Package: yarn
      Pin: origin "dl.yarnpkg.com"
      Pin-Priority: 1001

- name: Install nodejs and yarn
  apt:
    name: 
     - nodejs
     - yarn
    state: present
    update_cache: true
    allow_downgrade: yes
