#- name: Install cosmprund from source
#  block:
#    - name: Clone cosmprund repo
#      git:
#        repo: '{{ cosmprund_repo }}'
#        dest: '{{ user_dir }}/cosmprund'
#        #version: '{{ cosmprund_version }}'
#        update: yes
#        force: yes
#        depth: 1
#
#- name: Build and install cosmos-pruner
#      command: 'make install'
#      args:
#        chdir: '{{ user_dir }}/{{ cosmprund }}'
#      environment:
#        PATH: '{{ path }}'
#        GOPATH: '{{ user_dir }}/go'

- name: Install cosmprund from source
  block:
    - name: Clone cosmprund repo
      git:
        repo: '{{ cosmprund_repo }}'
        dest: '{{ user_dir }}/cosmprund'
        #version: '{{ node_version }}'
        update: yes
        force: yes
        depth: 1

    - name: Install cosmos-pruner
      command: '{{ item }}'
      args:
        chdir: '{{ user_dir }}/cosmprund'
      with_items:
        - 'make install'
      environment:
        PATH: '{{ path }}'
        GOPATH: '{{ user_dir }}/go'
