---
- name: Install jq and awscli
  become: true
  apt:
    name:
      - awscli
      - jq
    state: present
    update_cache: yes
  when: take_snapshots == true and snapshot_method == 'aws'

# snaps do not work in unprivileged LXC containers afaict :(
#- name: Install snapd
#  become: true
#  apt:
#    name: snapd
#    state: present
#    update_cache: yes

- name: Install lz4
  become: true
  apt:
    name: lz4
    state: present
    update_cache: yes

- name: Create directory
  file:
    path: '{{ user_dir }}/snapshot'
    state: directory
    mode: '0755'

- name: Clone and build cosmprund
  import_tasks: roles/support_snapshot/tasks/cosmprund.yml

- name: Copy snapshot script
  template:
    src: 'snapshot.sh.j2'
    dest: '{{ user_dir }}/snapshot/{{ network }}.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0700'

- name: Create cronjob
  cron:
    user: '{{ ansible_user }}'
    name: '{{ network }} snapshot'
    minute: '{{ snapshot_minute }}'
    hour: '{{ snapshot_hour }}'
    job: '/bin/bash {{ user_dir }}/snapshot/{{ network }}.sh'
